import Link from "next/link";
import LandingMotion from "./landing-motion";

const features = [
  ["01", "Website builder", "Publish a calm, credible clinic front door without handing your team a second system."],
  ["02", "Booking that respects time", "Offer real availability and keep conflicts out of the schedule."],
  ["03", "A live queue", "Give reception a shared view of who is waiting and what needs to happen next."],
  ["04", "A useful CRM", "Keep patient context, care teams, notes, and consent close to the work."],
  ["05", "Follow-ups that land", "Turn the small promises after a visit into visible, assignable work."],
];

const faqs = [
  ["Who is carefully for?", "Independent doctors and small clinics that want one dependable workspace for their public site and daily operations."],
  ["Does it replace our existing clinical record?", "No. carefully is focused on the clinic experience around your work: your website, booking, schedule, queue, CRM, and follow-up operations."],
  ["Can our team work with different permissions?", "Yes. Access is scoped by clinic, branch, role, and permission. The API remains the source of truth for every protected action."],
  ["Is there a template gallery?", "Not yet. We show the one preview surface that is currently built and fully renderable, rather than promising a gallery of unfinished templates."],
];

function MiniDashboard() {
  return <div className="product-dashboard" aria-label="Synthetic clinic dashboard preview"><div className="product-sidebar"><span className="product-mark">c/</span><span className="product-side-active">Overview</span><span>Schedule</span><span>Patients</span><span>Queue</span><span>Follow-ups</span></div><div className="product-main"><div className="product-top"><span>MONDAY · CLINIC TIME</span><b>VC</b></div><h2>Good morning, <i>team.</i></h2><div className="product-kpis"><span><small>Today</small><strong>12</strong><em>appointments</em></span><span><small>Waiting</small><strong>03</strong><em>in queue</em></span><span><small>Follow-ups</small><strong>07</strong><em>due now</em></span></div><div className="product-schedule"><div><small>YOUR DAY</small><b>Today&apos;s schedule</b></div><p><time>09:30</time><strong>New patient consultation</strong><em>confirmed</em></p><p><time>10:15</time><strong>Review · Dr. Vale</strong><em>in 45 min</em></p><p><time>11:00</time><strong>Follow-up appointment</strong><em>requested</em></p></div></div></div>;
}

function PhoneBooking() {
  return <div className="phone-frame" aria-label="Synthetic patient booking preview"><div className="phone-notch"/><div className="phone-screen"><span className="phone-brand">care/fully</span><small>BOOK A VISIT</small><h3>Choose a time<br /><i>that works.</i></h3><div className="phone-doctor"><span>DV</span><p><b>Dr. Vale</b><small>General medicine</small></p></div><div className="phone-slots"><b>Today</b><span>09:30</span><span className="selected-slot">10:15</span><span>11:00</span></div><button type="button">Continue <i>→</i></button></div></div>;
}

function PublishedSite() {
  return <div className="published-site" aria-label="Synthetic published clinic website preview"><div className="site-browser"><span/><span/><span/><em>vale-clinic.example</em></div><div className="site-body"><small>VALE FAMILY CLINIC</small><h3>Care that<br /><i>keeps pace.</i></h3><p>Thoughtful primary care for busy lives.</p><button type="button">Book a visit</button><div className="site-sun"/></div></div>;
}

export default function HomePage() {
  return <main className="landing-page">
    <LandingMotion />
    <div className="scroll-progress" aria-hidden="true" />
    <nav className="nav shell" aria-label="Primary navigation"><Link className="wordmark" href="/">care<span>/</span>fully</Link><div className="nav-links"><a href="#product">Product</a><a href="#how-it-works">How it works</a><a href="#security">Security</a><Link className="nav-cta" href="/login">Sign in <span>↗</span></Link></div></nav>
    <section className="landing-hero shell" aria-labelledby="hero-title"><div className="landing-hero-copy"><p className="eyebrow"><span className="eyebrow-dot"/> CLINIC OPERATIONS, WITH ROOM TO BREATHE</p><h1 id="hero-title">Make care feel <em>well run.</em></h1><p className="hero-lede">A thoughtful digital home for independent doctors and small clinics — from first impression to finished follow-up.</p><div className="hero-actions"><Link className="button button-primary" href="/login">Enter the workspace <span>→</span></Link><a className="text-link" href="#product">See the product <span>↓</span></a></div><div className="hero-proof"><span><b>●</b> Built around real clinic work</span><span><b>↗</b> Tenant-aware by design</span></div></div><div className="hero-composition"><MiniDashboard/><PhoneBooking/><PublishedSite/><span className="composition-note">the calmer day is in the details <i>✳</i></span></div></section>
    <section className="product-story shell" id="product" aria-labelledby="product-title"><div className="section-intro"><p className="eyebrow">ONE CONNECTED WORKSPACE</p><h2 id="product-title">The front door,<br /><em>the day itself.</em></h2></div><div className="story-copy"><p>carefully keeps the public experience and the private work in the same rhythm. Patients get a clear path in. Teams get a clear view of what comes next.</p><Link className="text-link" href="/login">Explore the workspace <span>→</span></Link></div></section>
    <section className="feature-bento shell" aria-label="Product capabilities">{features.map(([number, title, text], index) => <article className={`feature-tile feature-tile-${index + 1}`} key={number}><span className="feature-number">{number}</span><h3>{title}</h3><p>{text}</p>{index === 0 && <div className="tile-browser"><span>published / today</span><b>Vale<br /><i>Family Clinic</i></b></div>}{index === 1 && <div className="tile-checks"><span>09:30 <b>available</b></span><span>10:15 <b>held for you</b></span></div>}{index === 2 && <div className="tile-queue"><span>01</span><b>Amelia R.</b><em>waiting</em><span>02</span><b>Jon M.</b><em>ready</em></div>}{index === 3 && <div className="tile-notes"><span>last visit</span><b>“Feeling better.”</b><small>private care context</small></div>}{index === 4 && <div className="tile-follow"><span>FOLLOW-UP</span><b>Check in with Amelia</b><em>due today · assigned</em></div>}</article>)}</section>
    <section className="how-section" id="how-it-works" aria-labelledby="how-title"><div className="shell"><div className="section-intro"><p className="eyebrow">A SIMPLE HANDOFF</p><h2 id="how-title">From setup to<br /><em>steady days.</em></h2></div><div className="steps-grid"><article><span>01</span><h3>Onboard</h3><p>Set up the clinic, services, team roles, and the shape of your day.</p></article><article><span>02</span><h3>Publish</h3><p>Choose the one public surface that is ready to represent your clinic well.</p></article><article><span>03</span><h3>Run the day</h3><p>Move from request to appointment to follow-up with less context switching.</p></article></div></div></section>
    <section className="security-section shell" id="security" aria-labelledby="security-title"><div className="security-copy"><p className="eyebrow">QUIETLY SERIOUS ABOUT THE FOUNDATION</p><h2 id="security-title">Trust is part of<br /><em>the interface.</em></h2><p>These are product foundations, not marketing badges: tenant isolation, MFA-aware sessions, an audit trail for protected actions, and private file handling.</p></div><div className="security-list"><div><span>01</span><b>Tenant isolation</b><p>Clinic context is enforced in the data layer and API.</p></div><div><span>02</span><b>MFA-aware access</b><p>Protected workspace actions require an authenticated session.</p></div><div><span>03</span><b>Audit trail</b><p>Meaningful staff actions are recorded with an outcome.</p></div><div><span>04</span><b>Private files</b><p>Documents remain behind scoped access and scan status checks.</p></div></div></section>
    <section className="template-section shell" aria-labelledby="template-title"><div className="template-copy"><p className="eyebrow">THE FIRST PUBLISHED TEMPLATE</p><h2 id="template-title">One good preview<br /><em>beats five promises.</em></h2><p>See the clinic site surface that is fully renderable today. We will add more when they are ready to carry the same standard.</p><Link className="text-link" href="/vale-clinic">View the published preview <span>↗</span></Link></div><PublishedSite/></section>
    <section className="faq-section shell" aria-labelledby="faq-title"><div className="section-intro"><p className="eyebrow">GOOD QUESTIONS</p><h2 id="faq-title">A little more<br /><em>clarity.</em></h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="final-cta"><div className="shell"><p className="eyebrow">WHEN THE DAY FEELS FULL</p><h2>Make room for<br /><em>the important part.</em></h2><Link className="button button-light" href="/login">Open carefully <span>→</span></Link></div></section>
    <footer className="footer shell"><span className="wordmark">care<span>/</span>fully</span><span>Clinic operations, with room to breathe · <Link href="/privacy">Privacy</Link></span></footer>
  </main>;
}
