PERMISSIONS = {
    "clinic.read",
    "clinic.update",
    "branch.read",
    "branch.manage",
    "staff.read",
    "staff.manage",
    "staff.password_reset",
    "doctor.read",
    "doctor.manage",
    "service.read",
    "service.manage",
    "schedule.read",
    "schedule.manage",
    "appointment.read",
    "appointment.create",
    "appointment.manage",
    "appointment.approve",
    "appointment.cancel",
    "appointment.reschedule",
    "appointment.check_in",
    "queue.read",
    "queue.manage",
    "patient.read",
    "patient.create",
    "patient.update",
    "patient.archive",
    "patient.export",
    "patient.note.read",
    "patient.note.write",
    "patient.private_note.read",
    "patient.private_note.write",
    "patient.document.read",
    "patient.document.write",
    "patient.document.delete",
    "consent.read",
    "consent.manage",
    "followup.read",
    "followup.manage",
    "notification.read",
    "notification.manage",
    "website.read",
    "website.edit",
    "website.publish",
    "audit.read",
    "admin.clinic.manage",
    "admin.plan.manage",
    "admin.support.access",
    "admin.analytics.read",
}


def validate_permission_code(code: str) -> str:
    if code not in PERMISSIONS:
        raise ValueError(f"unknown permission code: {code}")
    return code
